[Ritesh/Umair] Added workflow trigger

diff --git a/.github/workflows/deploy_publish.yaml b/.github/workflows/deploy_publish.yaml
--- a/.github/workflows/deploy_publish.yaml
+++ b/.github/workflows/deploy_publish.yaml
@@ -48,3 +48,25 @@ jobs:
           file: Dockerfile
           push: true
           tags: bahmni/event-router-service:ipd-${{ github.run_number }}, bahmni/event-router-service:ipd
+
+  trigger-workflow:
+    name: Trigger workflow to deploy to docker env
+    needs:
+      - Trivy
+      - build-publish-docker
+    runs-on: ubuntu-latest
+    env:
+      ORG_NAME: cureinternational
+      REPOSITORY_NAME: cure-bahmni-docker
+      EVENT_TYPE: bahmni-ipd-event-router-service-event
+    steps:
+      - name: Create repository_dispatch
+        run: |
+          trigger_result=$(curl -s -o trigger_response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.BAHMNI_PAT }}' https://api.github.com/repos/${ORG_NAME}/${REPOSITORY_NAME}/dispatches -d '{"event_type":"'"${EVENT_TYPE}"'"}')
+          if [ $trigger_result == 204 ];then
+            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Success"
+          else
+            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Failed"
+            cat trigger_response.txt
+            exit 1
+          fi
